<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="Insumos.aspx.cs" Inherits="WebAplication.Insumos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container">

        <div class="form-row">
            <div class="form-group col-md-">
                <h2>Insumos</h2>
            </div>
          
        </div>

        <div class="form-row">
            <asp:Label Text="Nombre" ID="lblNombre" runat="server"></asp:Label>
            <asp:TextBox ID="txbNombre" runat="server"></asp:TextBox>
            <asp:Label Text="Medida " ID="lblMedida" runat="server"></asp:Label>

            <asp:DropDownList runat="server" ID="cboMedidas">
            </asp:DropDownList>
            <asp:Button CssClass="btn btn-primary" Text="Agregar" ID="BtnAgregar" runat="server" OnClick="BtnAgregar_Click"></asp:Button>
        </div>
    </div>

    <div class="form-row">
        <asp:GridView ID="dgvInsumos"  CssClass="table table-striped" runat="server" AutoGenerateColumns="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" EditRowStyle-BorderStyle="Dotted" UpdateMethod="Modificar">
            
        </asp:GridView>
    </div>
    <%-- --%>
</asp:Content>
