<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="Insumos.aspx.cs" Inherits="WebAplication.Insumos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container">

        <div class="form-row">
            <div class="form-group col-md-">
                <h2>Insumos</h2>
            </div>
        </div>

        <div class="form-row">
            <asp:Label Text="Nombre" ID="lblNombre" runat="server"></asp:Label>
            <asp:TextBox ID="txbNombre" runat="server">
                
            </asp:TextBox>
            <asp:Label Text="Medida " ID="lblMedida" runat="server"></asp:Label>


            <asp:DropDownList runat="server" ID="cboMedidas">
            </asp:DropDownList>
            <asp:Button Text="Agregar" ID="BtnAgregar" runat="server" OnClick="BtnAgregar_Click"></asp:Button>
        </div>
    </div>

    <div>
        <asp:GridView ID="dgvInsumos" runat="server"
            BackColor="White" ForeColor="#000066" BorderWidth="1px" CellPadding="3" AutoGenerateColumns="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="lightgreen" Font-Bold="True" ForeColor="Black" />
            <PagerStyle BackColor=" white" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
            <%--  --%>
        </asp:GridView>
    </div>
    <%-- --%>
</asp:Content>
